### ISSUE TITLE
Hand over the zone-crossing prototype

### ISSUE THREAD

**Issue by jirigrill** [jirigrill/eczema-helper#742]
## Question

Get the zone-crossing prototype into a state the owner can pick up on a phone, and hand it over with the numbers computed rather than argued.

**Split out of [#728](https://github.com/jirigrill/eczema-helper/issues/728)**, which now carries only the decision. This ticket builds and hands over; it decides nothing. `DAY-NAV-9` stays `OPEN` when it closes.

Follows the shape [#727](https://github.com/jirigrill/eczema-helper/issues/727) proved: build the comparison, measure it headlessly, hand it to the phone, and stop.

## Where it stands

The spike exists and runs at `~/Developer/eczema-ios-spikes/photo-placement-727`'s sibling, `~/Developer/eczema-ios-spikes/timezone-728/` — 7 Swift files, a `run.sh` and a `verify.sh`, plus 7 captured frames in `shots/`. It is **not handed over**: #728 has no comments, so none of this is discoverable from the tracker.

**What it already does.** Three candidate policies, side by side in one app, because the question is comparative:

- **A · `Pevné` (fixed)** — the date is set at log time and never recomputed. The spec's recorded recommendation, and the PWA's actual behaviour (`todayIso()`, `src/lib/utils/date.ts:14-16`).
- **B · `Přepočet` (reinterpret)** — every record's day is recomputed from its `createdAt` instant in the zone the phone is in now. The alternative #728 names.
- **C · `Pevné + zóna` (fixedHomeClock)** — date fixed as in A, but the record's *own* logged zone renders its time-of-day, so a caption reads the clock she actually saw.

The policies split the question into two axes that can be answered independently — what date a **new** record gets, and what date an **existing** record shows under. Worth stating in the hand-over: **all three answer the write side identically** (the device's local date), so only the read side is in dispute.

**A six-leg fixture** flies Prague → Auckland → Honolulu → Prague across 13 meals and 6 observations, and hits every case #728 names: leg 0→1 advances **two** calendar days (`2026-05-15` never lived), leg 2→3 stays on `2026-05-17` twice, leg 4→5 skips three more days.

**Two ways the zone is exercised**, deliberately: an in-app leg picker (so shapes flip side by side), and `./run.sh zone <id>`, which sets `SIMCTL_CHILD_TZ` so `TimeZone.current` genuinely reports that zone — the check that the in-app simulation is not lying about what Foundation does.

`./verify.sh` computes the tables on the host rather than reading them off a screenshot, on the grounds that the two facts the ticket turns on are arithmetic, not layout.

## Scope

- A `README.md` for the spike. `run.sh:19`, `Verify.swift:6` and `App.swift:16` all reference one and **it does not exist** — so the toolchain claims those comments make ("verified working on Xcode 27.0 / iOS 26 (see README.md §Verified)") are currently unbacked.
- Confirm it still builds and launches on the booted simulator, and re-capture `shots/` if the frames are stale.
- Post the hand-over comment on [#728](https://github.com/jirigrill/eczema-helper/issues/728): how to run it, what is on screen, the computed tables, and what to watch for while holding it. `#727`'s first comment is the model, including its explicit *"None of the above picks a shape. Over to you with the phone."*

**Not in scope:** choosing a policy (that is #728); the stranded-record and slot-collision findings, which the spike surfaced but which are their own tickets ([#E](E), [#F](F)); landing the research doc ([#741](https://github.com/jirigrill/eczema-helper/issues/741)).
